[package]
name = "warung-service-account-api"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
axum = "0.8.4"
dotenvy = "0.15.7"
tokio = { version = "1.46.1", features = ["full"] }

[dev-dependencies]
axum-test = "17.3.0"
